[tool.ruff]
# Select the rules for code formatting, imports, and type hints
select = ["E", "W", "F401", "I", "ANN"]

fixable = ["I"]

# Optional: Exclude specific files or directories
exclude = ["src/gui/"]

ignore = ["ANN101", "E501",  "ANN201", "E999"]

# Set the maximum line length (if formatting requires it)
line-length = 88

# Configure per-file ignores (e.g., ignore unused imports in `main.py`)
[tool.ruff.per-file-ignores]
"main.py" = ["F401"]

